server:
  port: 8002

spring:
  application:
    name: "food-court-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}




appDescription: "Plazoleta API"
appVersion: "1.0.0"
