server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver




appDescription: "Usuarios API"
appVersion: "1.0.0"